const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const multer = require('multer');
const path = require('path');

const app = express();
app.use(cors());
app.use(express.json());

// Serve the uploaded images so the website can display them
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

// Set up Multer to store files in the 'uploads' folder
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, 'uploads/'),
  filename: (req, file, cb) => cb(null, Date.now() + '-' + file.originalname)
});
const upload = multer({ storage });

// Connect to MongoDB
mongoose.connect('mongodb://localhost:27017/smartpicks');

const Product = mongoose.model('Product', {
  name: String,
  category: String,
  image: String, 
  desc: String,
  link: String
});

app.get('/api/products', async (req, res) => {
  const products = await Product.find();
  res.json(products);
});

// Notice we added 'upload.single("image")' here
app.post('/api/products', upload.single('image'), async (req, res) => {
  const newProduct = new Product({
    name: req.body.name,
    category: req.body.category,
    desc: req.body.desc,
    link: req.body.link,
    // Save the new file path generated by our server
    image: req.file ? `http://localhost:3000/uploads/${req.file.filename}` : ''
  });
  await newProduct.save();
  res.json(newProduct);
});

app.delete('/api/products/:id', async (req, res) => {
  await Product.findByIdAndDelete(req.params.id);
  res.json({ success: true });
});

app.listen(3000, () => console.log('Server running on http://localhost:3000'));